plugins {
    id 'idea'
    id 'application'
    id 'org.beryx.jlink' version '3.2.1'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

javafx {
    version = "25"
    modules = [ 'javafx.controls' ]
}

application {
    mainClass = "org.openjfx.isosurface.Main"
    mainModule = "IsosurfaceExtraction.main"
    applicationDefaultJvmArgs = [
        '--enable-native-access=javafx.graphics'
    ]
}

jlink {
    options = ['--strip-debug', '--no-header-files', '--no-man-pages']
    launcher {
        name = 'IsosurfaceExtraction'
    }
}
